apiVersion: apps/v1
kind: Deployment
metadata:
  name: uir-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: uir-framework
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"