apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../

namespace: uir-staging

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: uir-config
    behavior: merge
    literals:
      - log-level=DEBUG