apiVersion: apps/v1
kind: Deployment
metadata:
  name: uir-api
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: uir-framework
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"